version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
      - '3001'
    volumes:
      - ./tmp:/usr/src/app/tmp
    env_file:
      - .env
    restart: always