apps:
  georedv3:
    EXTERNAL_APP_URL: "http://localhost:3001"
    EXTERNAL_APP_API_KEY: "secret"
    EXTERNAL_APP_LINK_FIELDS: ["clientName", "username", "password"]
    EXTERNAL_APP_API_URL: "http://localhost:3001"
    EXTERNAL_API__GET_EXTERNAL_ID_ROUTE: "/googleauth/external-id"
    EXTERNAL_API__GET_JWT_ROUTE: "/googleauth/get_jwt"
  styx:
    EXTERNAL_APP_URL: "https://example.com/app2"
    EXTERNAL_APP_API_KEY: "your_api_key_2"
    EXTERNAL_APP_LINK_FIELDS: ["field3", "field4"]
    EXTERNAL_APP_API_URL: "https://api.example.com/app2"
    EXTERNAL_API__GET_EXTERNAL_ID_ROUTE: "/googleauth/external-id"
    EXTERNAL_API__GET_JWT_ROUTE: "/googleauth/get_jwt"
  google:
    openid_provider: true
    client_id: ""
    client_secret: ""
    redirect_url: "http://localhost:3000/auth/callback/google"
    scope: "profile email"
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
  gitlab:
    openid_provider: true
    client_id: ""
    client_secret: ""
    redirect_url: "http://localhost:3000/auth/callback/gitlab"
    scope: "openid profile email api read_api"
    auth_url: "https://gitlab.com/oauth/authorize"


