apps:
  georedv3local:
    EXTERNAL_APP_URL: "http://georedv3:8081/"
    EXTERNAL_APP_LINK_FIELDS: ["client", "login", "password"]
    EXTERNAL_APP_API_URL: "http://localhost:9002"
    EXTERNAL_API__GET_EXTERNAL_ID_ROUTE: "/public/auth/authentication"
    EXTERNAL_API__GET_JWT_ROUTE: "/public/auth/sso/get_token"
    EXTERNAL_APP_API_KEY: "__SSOLOGIN_API_KEY__"
  georedv3:
    EXTERNAL_APP_URL: "http://localhost:3001"
    EXTERNAL_APP_API_KEY: "secret"
    EXTERNAL_APP_LINK_FIELDS: ["clientName", "username", "password"]
    EXTERNAL_APP_API_URL: "http://localhost:3001"
    EXTERNAL_API__GET_EXTERNAL_ID_ROUTE: "/ssoauth/external-id"
    EXTERNAL_API__GET_JWT_ROUTE: "/ssoauth/get_jwt"
  styx:
    EXTERNAL_APP_URL: "https://example.com/app2"
    EXTERNAL_APP_API_KEY: "your_api_key_2"
    EXTERNAL_APP_LINK_FIELDS: ["field3", "field4"]
    EXTERNAL_APP_API_URL: "https://api.example.com/app2"
    EXTERNAL_API__GET_EXTERNAL_ID_ROUTE: "/ssoauth/external-id"
    EXTERNAL_API__GET_JWT_ROUTE: "/ssoauth/get_jwt"
  google:
    openid_provider: true
    client_id: ""
    client_secret: ""
    redirect_url: "http://localhost:3000/auth/callback/google"
    scope: "profile email"
    auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
  keycloak:
    openid_provider: true
    client_id: "your-client-id"
    client_secret: "your-client-secret"
    redirect_url: "http://localhost:3000/auth/callback/keycloak"
    scope: "openid profile email"
    auth_url: "http://localhost:8085/realms/master/protocol/openid-connect/auth"
    userinfo_endpoint: "http://localhost:8085/realms/master/protocol/openid-connect/userinfo"
    token_endpoint: "http://localhost:8085/realms/master/protocol/openid-connect/token"
  gitlab:
    openid_provider: true
    client_id: ""
    client_secret: ""
    redirect_url: "http://localhost:3000/auth/callback/gitlab"
    scope: "openid profile email api read_api"
    auth_url: "https://gitlab.com/oauth/authorize"
  auth0:
    openid_provider: true
    client_id: "MMfJCjmNeiu0dby32G38kj9wtRlA2pPa"
    client_secret: ""
    audience: "https://misitioba.eu.auth0.com/api/v2/"
    redirect_url: "http://localhost:3000/auth/callback/auth0"
    scope: "openid profile email"
    auth_url: "https://misitioba.eu.auth0.com/login"


